### ISSUE TITLE
1.21.1 please

### ISSUE THREAD

**Issue by aysaoif** [LasaJoniHD/CreeperRefund#2]
been using this plugin on all my servers, now that i am back to minecraft
would like to use it on my server again but it seems that the plugin isnt available for 1.21.1?

would also appreciate if you guys let me know whether i can still use the plugin eventhough its on 1.21, or that i will have to wait till the update is released

ggs

**Comment by LasaJoniHD** [comment]
CreeperRedund is now available for 1.21.1. A little tip from me: many small plugins work in newer versions without the need for an update. Just give it a try next time and see if it works or not.

**Comment by aysaoif** [comment]
> CreeperRedund is now available for 1.21.1. A little tip from me: many small plugins work in newer versions without the need for an update. Just give it a try next time and see if it works or not.

thanks!
